### ISSUE TITLE
v1.1.0 无法启动，1.0.0没问题

### ISSUE THREAD

**Issue by Pixellevel** [PiDanShouRouZhouXD/Sakura_Launcher_GUI#22]
窗口显示
'D:\software\Sakura' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

D:\software\Sakura GUI>

日志
[WARNING] 重名 GPU: NVIDIA GeForce RTX 4060 Ti, 已存在，忽略
[INFO] 更新 GPU 信息: GPUInfo(index=None, name='NVIDIA GeForce RTX 4060 Ti', gpu_type=<GPUType.NVIDIA: 1>, dedicated_gpu_memory=17175674880, dedicated_system_memory=None, shared_system_memory=None, avail_dedicated_gpu_memory=16083058688, ability=None)
[INFO] 检测到AMD GPU(正向列表): []
[INFO] 检测到AMD GPU(反向列表): []
[INFO] 模型路径: sakura-14b-qwen2.5-v1.0-q6k.gguf
[INFO] 模型名称: sakura-14b-qwen2.5-v1.0-q6k.gguf
[INFO] 尝试执行命令: D:\software\Sakura GUI\llama\llama-server.exe --version
[INFO] 版本输出: ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4060 Ti, compute capability 8.9, VMM: yes
version: 4011 (a6744e43)
built with MSVC 19.29.30156.0 for x64
[INFO] llama.cpp版本: 4011
[INFO] 版本大于等于3898，添加--slots参数
[INFO] 设置 CUDA_VISIBLE_DEVICES = 0
[INFO] 执行命令: D:\software\Sakura GUI\llama\llama-server.exe --model sakura-14b-qwen2.5-v1.0-q6k.gguf -c 2048 -ngl 200 -a sakura-14b-qwen2.5-v1.0-q6k.gguf --host 127.0.0.1 --port 8080 -np 1 --metrics --slots -fa --no-mmap
[INFO] 命令已在新的终端窗口中启动。

**Comment by Pixellevel** [comment]
好吧，因为文件夹名字有空格

**Comment by PiDanShouRouZhouXD** [comment]
可能是修Linux运行的时候把路径的引号删掉了，我看看能不能加回来
