### ISSUE TITLE
无法获取显卡列表

### ISSUE THREAD

**Issue by gzzhongqi** [PiDanShouRouZhouXD/Sakura_Launcher_GUI#24]
我是win11系统，3070显卡，不知道为什么显卡列表无法显示出我的显卡，列表中只有“自动”一个选项，在1.0版本即使显卡列表是空的，只要选自动还可以正常启动，实际启动后显卡也能被正常调用。更新到1.1后尝试启动时会直接报错，设置GPU环境变量时出错: cannot access local variable 'selected_gpu' where it is not associated with a value`。

更新：
稍微debug了一下发现原因了，gpu列表的抓取是靠nvidia-smi，但nvidia-smi默认并不在path里，所以获取显卡列表会出错，我手动把nvidia-smi加到了windows的path里面就好了。我猜其他windows用户估计也会有这个问题

日志：
[WARNING] 获取远程数据失败: https://ghp.ci/https://raw.githubusercontent.com/PiDanShouRouZhouXD/Sakura_Launcher_GUI/refs/heads/main/data.json HTTPSConnectionPool(host='ghp.ci', port=443): Max retries exceeded with url: /https://raw.githubusercontent.com/PiDanShouRouZhouXD/Sakura_Launcher_GUI/refs/heads/main/data.json (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000)')))
[WARNING] 重名 GPU: NVIDIA GeForce RTX 3070, 已存在，忽略
[INFO] 检测到AMD GPU(正向列表): []
[INFO] 检测到AMD GPU(反向列表): []
[WARNING] 未检测到NVIDIA或AMD GPU
[INFO] 未检测到NVIDIA或AMD GPU
[INFO] 模型路径: GalTransl-7B-v2.6-IQ4_XS.gguf
[INFO] 模型名称: GalTransl-7B-v2.6-IQ4_XS.gguf
[INFO] 尝试执行命令: C:\Users\gzzho\Downloads\SakuraLLM\llama\llama-server.exe --version
[INFO] 版本输出: ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3070, compute capability 8.6, VMM: yes
version: 3923 (becfd387)
built with MSVC 19.29.30154.0 for x64
[INFO] llama.cpp版本: 3923
[INFO] 版本大于等于3898，添加--slots参数
[INFO] 设置GPU环境变量时出错: cannot access local variable 'selected_gpu' where it is not associated with a value

**Comment by kurikomoe** [comment]
cmd.exe 里面执行 `nvidia-smi` ，看一下系统是否装了 `nvidia-smi` 相关命令

**Comment by PiDanShouRouZhouXD** [comment]
自动选项出错已经修复，将在beta版本更新，请耐心等待。

**Comment by gzzhongqi** [comment]
> cmd.exe/powershell.exe 里面执行 `nvidia-smi` ，看一下系统是否装了 `nvidia-smi` 相关命令

啊，我这边刚刚已经自己debug发现是nvidia-smi找不到的原因了，nvidia-smi在windows里默认是没有加到path上的，我加到path就好了，我猜大部分windows用户也会遇到这个bug

**Comment by kurikomoe** [comment]
实际上最新的 n 卡驱动会把 nvidia-smi 放到 `C:\windows\system32` 下面，理论上 2022 年及以后的新装机不会出现这个问题。

**Comment by gzzhongqi** [comment]
> 实际上最新的 n 卡驱动会把 nvidia-smi 放到 `C:\windows\system32` 下面，理论上 2022 年及以后的新装机不会出现这个问题。

没有吧，我刚发现找不到nvidia-smi时特意更新了最新的驱动，依旧找不到，后来我查了stackoverflow才在C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_adf5a840df867035这种莫名其妙的目录底下找到的

**Comment by gzzhongqi** [comment]
> 实际上最新的 n 卡驱动会把 nvidia-smi 放到 `C:\windows\system32` 下面，理论上 2022 年及以后的新装机不会出现这个问题。

似乎是我电脑path不知道什么时候彻底乱了，system32居然不在path底下，不知道是不是anaconda搞的鬼

**Comment by PiDanShouRouZhouXD** [comment]
v1.1.0-beta 修复了自动选项出错的问题，nvidia-smi有可能会于下个版本直接集成在启动器中
