### ISSUE TITLE
请问模 Sakura型介绍界面提供的prompt格式：这个要填哪里呀

### ISSUE THREAD

**Issue by wangzi7654321** [PiDanShouRouZhouXD/Sakura_Launcher_GUI#29]
Sakura型介绍界面提供的prompt格式：
        gpt_dict = [{
          "src": "原文1",
          "dst": "译文1",
          "info": "注释信息1",
        },]
        gpt_dict_text_list = []
        for gpt in gpt_dict:
            src = gpt['src']
            dst = gpt['dst']
            info = gpt['info'] if "info" in gpt.keys() else None
            if info:
                single = f"{src}->{dst} #{info}"
            else:
                single = f"{src}->{dst}"
            gpt_dict_text_list.append(single)

        gpt_dict_raw_text = "\n".join(gpt_dict_text_list)

        user_prompt = "根据以下术语表（可以为空）：\n" + gpt_dict_raw_text + "\n" + "将下面的日文文本根据对应关系和备注翻译成中文：" + japanese
        prompt = "<|im_start|>system\n你是一个轻小说翻译模型，可以流畅通顺地以日本轻小说的风格将日文翻译成简体中文，并联系上下文正确使用人称代词，不擅自添加原文中没有的代词。<|im_end|>\n" \ # system prompt
        + "<|im_start|>user\n" + user_prompt + "<|im_end|>\n" \ # user prompt
        + "<|im_start|>assistant\n" # assistant prompt start

        # 如果术语表为空，也可以使用如下prompt（在术语表为空时更加推荐）
        user_prompt = "将下面的日文文本翻译成中文：" + japanese
        prompt = "<|im_start|>system\n你是一个轻小说翻译模型，可以流畅通顺地以日本轻小说的风格将日文翻译成简体中文，并联系上下文正确使用人称代词，不擅自添加原文中没有的代词。<|im_end|>\n" \ # system prompt
        + "<|im_start|>user\n" + user_prompt + "<|im_end|>\n" \ # user prompt
        + "<|im_start|>assistant\n" # assistant prompt start
        gpt_dict = [{
          "src": "原文1",
          "dst": "译文1",
          "info": "注释信息1",
        },]
        gpt_dict_text_list = []
        for gpt in gpt_dict:
            src = gpt['src']
            dst = gpt['dst']
            info = gpt['info'] if "info" in gpt.keys() else None
            if info:
                single = f"{src}->{dst} #{info}"
            else:
                single = f"{src}->{dst}"
            gpt_dict_text_list.append(single)

        gpt_dict_raw_text = "\n".join(gpt_dict_text_list)

        user_prompt = "根据以下术语表（可以为空）：\n" + gpt_dict_raw_text + "\n" + "将下面的日文文本根据对应关系和备注翻译成中文：" + japanese
        prompt = "<|im_start|>system\n你是一个轻小说翻译模型，可以流畅通顺地以日本轻小说的风格将日文翻译成简体中文，并联系上下文正确使用人称代词，不擅自添加原文中没有的代词。<|im_end|>\n" \ # system prompt
        + "<|im_start|>user\n" + user_prompt + "<|im_end|>\n" \ # user prompt
        + "<|im_start|>assistant\n" # assistant prompt start

        # 如果术语表为空，也可以使用如下prompt（在术语表为空时更加推荐）
        user_prompt = "将下面的日文文本翻译成中文：" + japanese
        prompt = "<|im_start|>system\n你是一个轻小说翻译模型，可以流畅通顺地以日本轻小说的风格将日文翻译成简体中文，并联系上下文正确使用人称代词，不擅自添加原文中没有的代词。<|im_end|>\n" \ # system prompt
        + "<|im_start|>user\n" + user_prompt + "<|im_end|>\n" \ # user prompt
        + "<|im_start|>assistant\n" # assistant prompt start
请问这个要填哪里呀？找不到填的地方

**Comment by kurikomoe** [comment]
本 repo 只是提供 api 接口，具体的 prompt 由上层应用调用者提供。
> 可以理解为启动器只是提供了 chatgpt 的对话框，怎么往对话框填信息是调用者的责任。

**Comment by wangzi7654321** [comment]
> 本 repo 只是提供 api 接口，具体的 prompt 由上层应用调用者提供。
> 
> > 可以理解为启动器只是提供了 chatgpt 的对话框，怎么往对话框填信息是调用者的责任。

意思要问前端吗？
请问Sakura型介绍界面的
推理与解码参数： 参数 值 temperature 0.1 top p 0.3 do sample True beams number 1 repetition penalty 1 max new token 512 min new token 1 这些是什么 怎么使用

**Comment by wangzi7654321** [comment]
> 本 repo 只是提供 api 接口，具体的 prompt 由上层应用调用者提供。
> 
> > 可以理解为启动器只是提供了 chatgpt 的对话框，怎么往对话框填信息是调用者的责任。

自定义命令：
%cmd%会被替换为GUI生成的完整启动命令，
%cmd_raw% 会替换成GUI生成的命令和模型选项，但不包括其他选项 请问这个是什么 是不是可以通过这个？

**Comment by huang007-cmd** [comment]
大佬，搞定了吗
