### ISSUE TITLE
下载出错10054

### ISSUE THREAD

**Issue by livlinglon** [PiDanShouRouZhouXD/Sakura_Launcher_GUI#35]
如图，求问该怎么解决，选github源也不行，需要什么特殊设置吗？
![屏幕截图 2024-12-26 023015](https://github.com/user-attachments/assets/9b1a59c8-f93e-408c-a8c7-a76bedf17304)
另外，[cudart-llama-bin-win-cu12.2.0-x64.zip](https://github.com/ggerganov/llama.cpp/releases/download/b3923/cudart-llama-bin-win-cu12.2.0-x64.zip)这个文件无法正常下载，普通情况点击下载无反应，使用IDM拦截后会出一个不知道怎么回事的输入账号的环节（如图）
![屏幕截图 2024-12-26 025502](https://github.com/user-attachments/assets/cb030d42-613e-4f2a-a8e5-4c4344aaed29)

**Comment by livlinglon** [comment]
手动从GitHub上的单独分别下载的[cudart-llama-bin-win-cu12.2.0-x64.zip](https://github.com/ggerganov/llama.cpp/releases/download/b3923/cudart-llama-bin-win-cu12.2.0-x64.zip)和[llama-b3923-bin-win-cuda-cu12.2.0-x64.zip](https://github.com/ggerganov/llama.cpp/releases/download/b3923/llama-b3923-bin-win-cuda-cu12.2.0-x64.zip)这两个文件，前一个会出上图的问题，后者却不会，就很怪

**Comment by kurikomoe** [comment]
Connection Rest 多半是没开梯子，从 GitHub 下载需要翻墙。
IDM 弹出输入帐号密码多半是因为连接失败，于是尝试输入帐号密码试试（也有可能是 IP 太脏了导致触发 GitHub 风控了之类的）

**Comment by livlinglon** [comment]
确实是翻墙问题，我用的是steam++的GitHub加速服务，换梯子就好了
