### ISSUE TITLE
An Amateur Seeking Help

### ISSUE THREAD

**Issue by Wenitakk** [PiDanShouRouZhouXD/Sakura_Launcher_GUI#5]
只是一个文字游戏爱好者，非计算机专业相关人士，想问问这个模型或者启动器不适配英特尔显卡么？我的显卡是英特尔锐炬Xe显卡。请问如何解决呢T T

**Comment by PiDanShouRouZhouXD** [comment]
不建议非专业人士尝试使用Intel显卡（尤其是核显）运行Sakura。
如果你执意要这么做，请参考 https://books.fishhawk.top/forum/6701b47baad73858badcab01 。这需要一定的计算机知识，不推荐完全没有基础知识的人尝试。
另外，核显的速度一般都很慢，可能不会明显快于纯CPU运行。
